### ISSUE TITLE
Auto minify the CSS

### ISSUE THREAD

**Issue by Nandaleio** [fordus/shadcn-classless#5]
It would be great to have a auto minify the CSS when commiting/merging to the main branch.

Here is an example I stole from [boltcss](https://github.com/tbolt/boltcss/blob/main/.github/workflows/minifycss.yml) 

```
name: Minify CSS
on:
  pull_request:
    types: [opened, reopened]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: auto minify the files
        uses: nizarmah/auto-minify@v3

      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: Add auto minified files"
```
